# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 513a30f5f520695d39d0e6afa93cc7f036a452d10d8aa7d3c366a67efa23adff41de058abcc55cb4bdf28e11d5f717f61eb6aed50c055e9b6731d46b72355c4d

test:
  secret_key_base: 6fcaefe7a6f37a5d93537b3b3a0fc227d884d3d29305d0754e8e10b9a63ad6c6c8dd84c18b15a0f0b73200fcb2ed6c80631de11b214d38869354d57a840b8b07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
